Loaded dependency [numpy/1.23.3-python-3.10.7-openblas-0.3.21]: openblas/0.3.21
Loaded dependency [python3/3.10.7]: gcc/11.3.0-binutils-2.38
Loaded dependency [numpy/1.23.3-python-3.10.7-openblas-0.3.21]: python3/3.10.7
Loaded dependency [pandas/1.4.4-python-3.10.7]: numpy/1.23.3-python-3.10.7-openblas-0.3.21
Loaded module: pandas/1.4.4-python-3.10.7

Loading pandas/1.4.4-python-3.10.7
  Loading requirement: openblas/0.3.21 gcc/11.3.0-binutils-2.38 python3/3.10.7
    numpy/1.23.3-python-3.10.7-openblas-0.3.21
Loaded module: matplotlib/3.6.0-numpy-1.23.3-python-3.10.7
Loaded module: cuda/11.6
Global seed set to 42
Traceback (most recent call last):
  File "/zhome/56/e/155505/Desktop/DeepLearningProject/experiment_main.py", line 105, in <module>
    main()
  File "/zhome/56/e/155505/Desktop/DeepLearningProject/experiment_main.py", line 100, in main
    fit_model(model, params, experiment_name, global_seed, max_epochs)
  File "/zhome/56/e/155505/Desktop/DeepLearningProject/experiment_helpers.py", line 85, in fit_model
    trainer = get_trainer(params, exp_name, global_seed, max_epochs)
  File "/zhome/56/e/155505/Desktop/DeepLearningProject/experiment_helpers.py", line 37, in get_trainer
    save_dir = os.path.join(params.project_dir, 'experiments', f'{exp_name}_{global_seed}')
AttributeError: 'AttrDict' object has no attribute 'project_dir'. Did you mean: 'project_dir_root'?
